modLoader="javafml"
loaderVersion="[52,)"
license="All Rights Reserved"

[[mods]]
modId="fdmod"
version="1.0.0"
displayName="FD Mod"

authors="faiden-dev"
description='''Mod where I add whatever I want.'''

[[dependencies.fdmod]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.fdmod]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"